# Generated by Django 5.0.1 on 2024-03-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, default='', upload_to='eduprod/static'),
        ),
    ]
