# Generated by Django 5.0.3 on 2024-03-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0002_question_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='question',
            name='answertextA',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='answertextB',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='answertextD',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='hasmultiplechoice',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=1000),
        ),
    ]
