# Generated by Django 5.0.3 on 2024-03-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0003_remove_question_answer_text_question_answertexta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answertextC',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='answertextA',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='answertextB',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='answertextD',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=1000),
        ),
    ]
