# Generated by Django 5.0.3 on 2024-03-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0004_question_answertextc_alter_question_answertexta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correctanswer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='answertextA',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
